[mypy]
python_version = 3.12

[mypy-google.*]
ignore_missing_imports = True

[mypy-httpx]
ignore_missing_imports = True

[mypy-eth_account]
ignore_missing_imports = True

[mypy-eth_account.messages]
ignore_missing_imports = True

[mypy-eth_utils]
ignore_missing_imports = True

[mypy-websockets]
ignore_missing_imports = True

[mypy-certifi]
ignore_missing_imports = True

[mypy-optuna.*]
ignore_missing_imports = True

[mypy-yaml]
ignore_missing_imports = True

[mypy-numpy.*]
ignore_missing_imports = True

[mypy-pandas.*]
ignore_missing_imports = True

[mypy-scipy.*]
ignore_missing_imports = True
